### PR TITLE
Support React Native 0.59.x

### PR DESCRIPTION
**Pull request by mkremer-jemmic**
This PR provides support for React Native from version 0.59.0 up to 0.59.10.
There wasn't any specific patch to apply, so this PR only consists of files using require_relative.

### CODE REVIEW

**Comment by orta** [comment]
,last should have CI fixed

**Comment by Nunnery** [comment]
Can you rebase this just so we can get a successful Travis build?

**Comment by Nunnery** [comment]
Tested out fine for me.

**Comment by simonedavico** [comment]
Sorry to hijack the PR thread :( how did you test this? I just tried to install the plugin through Bundler, but the version I get (in my `Gemfile.lock`) is `2019.03.19.11`. Inspecting the gem I see only support for React Native versions up to `0.58.6`.

Did I somehow install an old gem?

**Comment by Nunnery** [comment]
That's the most recent version available on rubygems.org. The CI didn't publish the newest merge correctly. Hopefully it'll be fixed shortly.

**Comment by simonedavico** [comment]
Thanks!

**Comment by shercoder** [comment]
Still seeing 2019.03.19.11, any ETA on when this will be fixed?

**Comment by Nunnery** [comment]
Currently, the issue is that Travis CI cannot deploy the gem due to MFA.

As far as I can tell, there are three options (in no particular order):
1. @orta publishes the gem manually whenever an update is needed, as the gem is published by him.
2. orta disables MFA on his RubyGems account.
3. orta adds someone else as a maintainer on RubyGems in order to publish the gem via their account.

**Pull request merged**
